[package]
name = "aoc-lib"
version = "0.1.0"
edition = "2021"
authors = ["Keval Kapdee"]
description = "A library that lets you focus on problem-solving rather than boilerplate when doing Advent of Code"
license = "MIT"
license-file = "LICENCE"
readme = "README.md"
repository = "https://github.com/thechubbypanda/aoc-lib"

[lib]
name = "aoc"
path = "src/lib.rs"
